
name: one

# Controls when the action will run. 
on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
    
      - name: trigger external
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(JSON.stringify(context))
            let {owner, repo} = context.repo()
            await github.git.createTag({
                owner,
                repo,
                ref: context.ref,
                tag: "1.0.0"
              })
            console.log("done")
            
