
name: one

# Controls when the action will run. 
on:
  push:
    branches: 
    - master
    - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: action hold
        uses: phish108/release-check@main
        id: isrelease
        with:
          protected-paths: | 
            README.md
            LICENSE
            .eslintrc
      - run: | 
          echo '${{ github.sha }}'
          echo '${{ steps.isrelease.outputs.proceed }}'
          echo '${{ steps.isrelease.outputs.hold_protected }}'
          echo '${{ steps.isrelease.outputs.hold_development }}'

      - name: check hold
        id: release
        uses: phish108/release-check@1.0.9
        
      - name: trigger external
        uses: actions/github-script@v3
        if: ${{ steps.release.outputs.proceed == "true" }}
        with:
          github-token: ${{ secrets.TRIGGER_TOKEN }}
          script: |
            core.info("release via task two")
            await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.ref,
                workflow_id: "two.yml",
                inputs: {"funny": JSON.stringify({foo: "bar"}) }
            })
      