
name: one

# Controls when the action will run. 
on:
  push:
    branch: 
    - master
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - id: chg_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: json
      
      - run: echo "${{ steps.chg_files.output }}"

      - name: trigger external
        uses: actions/github-script@v3
        env:
          DATA: ${{ steps.chg_files.output.all }}
        with:
          github-token: ${{ secrets.TRIGGER_TOKEN }}
          script: |
            console.log(process.env.DATA)
            await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.ref,
                workflow_id: "two.yml"
              })
            console.log("done")
            
