
name: one

# Controls when the action will run. 
on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      #- id: files
      #  uses: jitterbit/get-changed-files@v1
    
      - name: trigger external
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.TRIGGER_TOKEN }}
          script: |
            console.log(JSON.stringify(context))
            await github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/v1.0.3",
                object: context.sha,
                type: "commit",
                message: "release v1.0.3"
              })
            console.log("done")
            
