
name: one

# Controls when the action will run. 
on:
  push:
    branch: 
    - master
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      #- id: files
      #  uses: jitterbit/get-changed-files@v1
    
      - name: trigger external
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.TRIGGER_TOKEN }}
          script: |
            version = "v1.0.7"
            console.log(JSON.stringify(context))
            if (context.ref_type === "tag") 
              exit(1)
            await github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/{version}`,
                sha: context.sha,
                type: "commit",
                message: `release {version}`
              })
            console.log("done")
            
