
name: two

# Controls when the action will run. 
on:  
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps: 
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - uses: actions/github-script@v3
        with:
          script: |
            console.log("hello")
            console.log(JSON.stringify(context))